// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoRuntime.proto

package zermia.proto;

public final class ProtoRuntime {
  private ProtoRuntime() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConnectionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string replicaID = 1;</code>
     */
    java.lang.String getReplicaID();
    /**
     * <code>optional string replicaID = 1;</code>
     */
    com.google.protobuf.ByteString
        getReplicaIDBytes();
  }
  /**
   * <pre>
   *----------------------------------------------------------------------------------//
   * </pre>
   *
   * Protobuf type {@code ConnectionRequest}
   */
  public  static final class ConnectionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConnectionRequest)
      ConnectionRequestOrBuilder {
    // Use ConnectionRequest.newBuilder() to construct.
    private ConnectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionRequest() {
      replicaID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConnectionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              replicaID_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zermia.proto.ProtoRuntime.internal_static_ConnectionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zermia.proto.ProtoRuntime.internal_static_ConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zermia.proto.ProtoRuntime.ConnectionRequest.class, zermia.proto.ProtoRuntime.ConnectionRequest.Builder.class);
    }

    public static final int REPLICAID_FIELD_NUMBER = 1;
    private volatile java.lang.Object replicaID_;
    /**
     * <code>optional string replicaID = 1;</code>
     */
    public java.lang.String getReplicaID() {
      java.lang.Object ref = replicaID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replicaID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string replicaID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplicaIDBytes() {
      java.lang.Object ref = replicaID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replicaID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReplicaIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replicaID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReplicaIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replicaID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zermia.proto.ProtoRuntime.ConnectionRequest)) {
        return super.equals(obj);
      }
      zermia.proto.ProtoRuntime.ConnectionRequest other = (zermia.proto.ProtoRuntime.ConnectionRequest) obj;

      boolean result = true;
      result = result && getReplicaID()
          .equals(other.getReplicaID());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REPLICAID_FIELD_NUMBER;
      hash = (53 * hash) + getReplicaID().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zermia.proto.ProtoRuntime.ConnectionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *----------------------------------------------------------------------------------//
     * </pre>
     *
     * Protobuf type {@code ConnectionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConnectionRequest)
        zermia.proto.ProtoRuntime.ConnectionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zermia.proto.ProtoRuntime.ConnectionRequest.class, zermia.proto.ProtoRuntime.ConnectionRequest.Builder.class);
      }

      // Construct using zermia.proto.ProtoRuntime.ConnectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replicaID_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionRequest_descriptor;
      }

      public zermia.proto.ProtoRuntime.ConnectionRequest getDefaultInstanceForType() {
        return zermia.proto.ProtoRuntime.ConnectionRequest.getDefaultInstance();
      }

      public zermia.proto.ProtoRuntime.ConnectionRequest build() {
        zermia.proto.ProtoRuntime.ConnectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zermia.proto.ProtoRuntime.ConnectionRequest buildPartial() {
        zermia.proto.ProtoRuntime.ConnectionRequest result = new zermia.proto.ProtoRuntime.ConnectionRequest(this);
        result.replicaID_ = replicaID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zermia.proto.ProtoRuntime.ConnectionRequest) {
          return mergeFrom((zermia.proto.ProtoRuntime.ConnectionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zermia.proto.ProtoRuntime.ConnectionRequest other) {
        if (other == zermia.proto.ProtoRuntime.ConnectionRequest.getDefaultInstance()) return this;
        if (!other.getReplicaID().isEmpty()) {
          replicaID_ = other.replicaID_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zermia.proto.ProtoRuntime.ConnectionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zermia.proto.ProtoRuntime.ConnectionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object replicaID_ = "";
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public java.lang.String getReplicaID() {
        java.lang.Object ref = replicaID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replicaID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReplicaIDBytes() {
        java.lang.Object ref = replicaID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replicaID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder setReplicaID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replicaID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder clearReplicaID() {
        
        replicaID_ = getDefaultInstance().getReplicaID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder setReplicaIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replicaID_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ConnectionRequest)
    }

    // @@protoc_insertion_point(class_scope:ConnectionRequest)
    private static final zermia.proto.ProtoRuntime.ConnectionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zermia.proto.ProtoRuntime.ConnectionRequest();
    }

    public static zermia.proto.ProtoRuntime.ConnectionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConnectionRequest>() {
      public ConnectionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConnectionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionRequest> getParserForType() {
      return PARSER;
    }

    public zermia.proto.ProtoRuntime.ConnectionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectionReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConnectionReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool connectionStatus = 1;</code>
     */
    boolean getConnectionStatus();

    /**
     * <code>optional bool replicaStatus = 2;</code>
     */
    boolean getReplicaStatus();
  }
  /**
   * Protobuf type {@code ConnectionReply}
   */
  public  static final class ConnectionReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConnectionReply)
      ConnectionReplyOrBuilder {
    // Use ConnectionReply.newBuilder() to construct.
    private ConnectionReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionReply() {
      connectionStatus_ = false;
      replicaStatus_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConnectionReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              connectionStatus_ = input.readBool();
              break;
            }
            case 16: {

              replicaStatus_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zermia.proto.ProtoRuntime.internal_static_ConnectionReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zermia.proto.ProtoRuntime.internal_static_ConnectionReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zermia.proto.ProtoRuntime.ConnectionReply.class, zermia.proto.ProtoRuntime.ConnectionReply.Builder.class);
    }

    public static final int CONNECTIONSTATUS_FIELD_NUMBER = 1;
    private boolean connectionStatus_;
    /**
     * <code>optional bool connectionStatus = 1;</code>
     */
    public boolean getConnectionStatus() {
      return connectionStatus_;
    }

    public static final int REPLICASTATUS_FIELD_NUMBER = 2;
    private boolean replicaStatus_;
    /**
     * <code>optional bool replicaStatus = 2;</code>
     */
    public boolean getReplicaStatus() {
      return replicaStatus_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connectionStatus_ != false) {
        output.writeBool(1, connectionStatus_);
      }
      if (replicaStatus_ != false) {
        output.writeBool(2, replicaStatus_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connectionStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, connectionStatus_);
      }
      if (replicaStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, replicaStatus_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zermia.proto.ProtoRuntime.ConnectionReply)) {
        return super.equals(obj);
      }
      zermia.proto.ProtoRuntime.ConnectionReply other = (zermia.proto.ProtoRuntime.ConnectionReply) obj;

      boolean result = true;
      result = result && (getConnectionStatus()
          == other.getConnectionStatus());
      result = result && (getReplicaStatus()
          == other.getReplicaStatus());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CONNECTIONSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConnectionStatus());
      hash = (37 * hash) + REPLICASTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReplicaStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.ConnectionReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zermia.proto.ProtoRuntime.ConnectionReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConnectionReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConnectionReply)
        zermia.proto.ProtoRuntime.ConnectionReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zermia.proto.ProtoRuntime.ConnectionReply.class, zermia.proto.ProtoRuntime.ConnectionReply.Builder.class);
      }

      // Construct using zermia.proto.ProtoRuntime.ConnectionReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        connectionStatus_ = false;

        replicaStatus_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zermia.proto.ProtoRuntime.internal_static_ConnectionReply_descriptor;
      }

      public zermia.proto.ProtoRuntime.ConnectionReply getDefaultInstanceForType() {
        return zermia.proto.ProtoRuntime.ConnectionReply.getDefaultInstance();
      }

      public zermia.proto.ProtoRuntime.ConnectionReply build() {
        zermia.proto.ProtoRuntime.ConnectionReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zermia.proto.ProtoRuntime.ConnectionReply buildPartial() {
        zermia.proto.ProtoRuntime.ConnectionReply result = new zermia.proto.ProtoRuntime.ConnectionReply(this);
        result.connectionStatus_ = connectionStatus_;
        result.replicaStatus_ = replicaStatus_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zermia.proto.ProtoRuntime.ConnectionReply) {
          return mergeFrom((zermia.proto.ProtoRuntime.ConnectionReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zermia.proto.ProtoRuntime.ConnectionReply other) {
        if (other == zermia.proto.ProtoRuntime.ConnectionReply.getDefaultInstance()) return this;
        if (other.getConnectionStatus() != false) {
          setConnectionStatus(other.getConnectionStatus());
        }
        if (other.getReplicaStatus() != false) {
          setReplicaStatus(other.getReplicaStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zermia.proto.ProtoRuntime.ConnectionReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zermia.proto.ProtoRuntime.ConnectionReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean connectionStatus_ ;
      /**
       * <code>optional bool connectionStatus = 1;</code>
       */
      public boolean getConnectionStatus() {
        return connectionStatus_;
      }
      /**
       * <code>optional bool connectionStatus = 1;</code>
       */
      public Builder setConnectionStatus(boolean value) {
        
        connectionStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connectionStatus = 1;</code>
       */
      public Builder clearConnectionStatus() {
        
        connectionStatus_ = false;
        onChanged();
        return this;
      }

      private boolean replicaStatus_ ;
      /**
       * <code>optional bool replicaStatus = 2;</code>
       */
      public boolean getReplicaStatus() {
        return replicaStatus_;
      }
      /**
       * <code>optional bool replicaStatus = 2;</code>
       */
      public Builder setReplicaStatus(boolean value) {
        
        replicaStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool replicaStatus = 2;</code>
       */
      public Builder clearReplicaStatus() {
        
        replicaStatus_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ConnectionReply)
    }

    // @@protoc_insertion_point(class_scope:ConnectionReply)
    private static final zermia.proto.ProtoRuntime.ConnectionReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zermia.proto.ProtoRuntime.ConnectionReply();
    }

    public static zermia.proto.ProtoRuntime.ConnectionReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionReply>
        PARSER = new com.google.protobuf.AbstractParser<ConnectionReply>() {
      public ConnectionReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConnectionReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionReply> getParserForType() {
      return PARSER;
    }

    public zermia.proto.ProtoRuntime.ConnectionReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FaultActivationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FaultActivationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string replicaID = 1;</code>
     */
    java.lang.String getReplicaID();
    /**
     * <code>optional string replicaID = 1;</code>
     */
    com.google.protobuf.ByteString
        getReplicaIDBytes();

    /**
     * <code>optional int32 currentRun = 2;</code>
     */
    int getCurrentRun();
  }
  /**
   * <pre>
   *----------------------------------------------------------------------------------//
   * </pre>
   *
   * Protobuf type {@code FaultActivationRequest}
   */
  public  static final class FaultActivationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FaultActivationRequest)
      FaultActivationRequestOrBuilder {
    // Use FaultActivationRequest.newBuilder() to construct.
    private FaultActivationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FaultActivationRequest() {
      replicaID_ = "";
      currentRun_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FaultActivationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              replicaID_ = s;
              break;
            }
            case 16: {

              currentRun_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zermia.proto.ProtoRuntime.internal_static_FaultActivationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zermia.proto.ProtoRuntime.internal_static_FaultActivationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zermia.proto.ProtoRuntime.FaultActivationRequest.class, zermia.proto.ProtoRuntime.FaultActivationRequest.Builder.class);
    }

    public static final int REPLICAID_FIELD_NUMBER = 1;
    private volatile java.lang.Object replicaID_;
    /**
     * <code>optional string replicaID = 1;</code>
     */
    public java.lang.String getReplicaID() {
      java.lang.Object ref = replicaID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replicaID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string replicaID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplicaIDBytes() {
      java.lang.Object ref = replicaID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replicaID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTRUN_FIELD_NUMBER = 2;
    private int currentRun_;
    /**
     * <code>optional int32 currentRun = 2;</code>
     */
    public int getCurrentRun() {
      return currentRun_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReplicaIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replicaID_);
      }
      if (currentRun_ != 0) {
        output.writeInt32(2, currentRun_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReplicaIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replicaID_);
      }
      if (currentRun_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentRun_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zermia.proto.ProtoRuntime.FaultActivationRequest)) {
        return super.equals(obj);
      }
      zermia.proto.ProtoRuntime.FaultActivationRequest other = (zermia.proto.ProtoRuntime.FaultActivationRequest) obj;

      boolean result = true;
      result = result && getReplicaID()
          .equals(other.getReplicaID());
      result = result && (getCurrentRun()
          == other.getCurrentRun());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REPLICAID_FIELD_NUMBER;
      hash = (53 * hash) + getReplicaID().hashCode();
      hash = (37 * hash) + CURRENTRUN_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRun();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zermia.proto.ProtoRuntime.FaultActivationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *----------------------------------------------------------------------------------//
     * </pre>
     *
     * Protobuf type {@code FaultActivationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FaultActivationRequest)
        zermia.proto.ProtoRuntime.FaultActivationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zermia.proto.ProtoRuntime.FaultActivationRequest.class, zermia.proto.ProtoRuntime.FaultActivationRequest.Builder.class);
      }

      // Construct using zermia.proto.ProtoRuntime.FaultActivationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replicaID_ = "";

        currentRun_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationRequest_descriptor;
      }

      public zermia.proto.ProtoRuntime.FaultActivationRequest getDefaultInstanceForType() {
        return zermia.proto.ProtoRuntime.FaultActivationRequest.getDefaultInstance();
      }

      public zermia.proto.ProtoRuntime.FaultActivationRequest build() {
        zermia.proto.ProtoRuntime.FaultActivationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zermia.proto.ProtoRuntime.FaultActivationRequest buildPartial() {
        zermia.proto.ProtoRuntime.FaultActivationRequest result = new zermia.proto.ProtoRuntime.FaultActivationRequest(this);
        result.replicaID_ = replicaID_;
        result.currentRun_ = currentRun_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zermia.proto.ProtoRuntime.FaultActivationRequest) {
          return mergeFrom((zermia.proto.ProtoRuntime.FaultActivationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zermia.proto.ProtoRuntime.FaultActivationRequest other) {
        if (other == zermia.proto.ProtoRuntime.FaultActivationRequest.getDefaultInstance()) return this;
        if (!other.getReplicaID().isEmpty()) {
          replicaID_ = other.replicaID_;
          onChanged();
        }
        if (other.getCurrentRun() != 0) {
          setCurrentRun(other.getCurrentRun());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zermia.proto.ProtoRuntime.FaultActivationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zermia.proto.ProtoRuntime.FaultActivationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object replicaID_ = "";
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public java.lang.String getReplicaID() {
        java.lang.Object ref = replicaID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replicaID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReplicaIDBytes() {
        java.lang.Object ref = replicaID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replicaID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder setReplicaID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replicaID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder clearReplicaID() {
        
        replicaID_ = getDefaultInstance().getReplicaID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string replicaID = 1;</code>
       */
      public Builder setReplicaIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replicaID_ = value;
        onChanged();
        return this;
      }

      private int currentRun_ ;
      /**
       * <code>optional int32 currentRun = 2;</code>
       */
      public int getCurrentRun() {
        return currentRun_;
      }
      /**
       * <code>optional int32 currentRun = 2;</code>
       */
      public Builder setCurrentRun(int value) {
        
        currentRun_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 currentRun = 2;</code>
       */
      public Builder clearCurrentRun() {
        
        currentRun_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FaultActivationRequest)
    }

    // @@protoc_insertion_point(class_scope:FaultActivationRequest)
    private static final zermia.proto.ProtoRuntime.FaultActivationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zermia.proto.ProtoRuntime.FaultActivationRequest();
    }

    public static zermia.proto.ProtoRuntime.FaultActivationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FaultActivationRequest>
        PARSER = new com.google.protobuf.AbstractParser<FaultActivationRequest>() {
      public FaultActivationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FaultActivationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FaultActivationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FaultActivationRequest> getParserForType() {
      return PARSER;
    }

    public zermia.proto.ProtoRuntime.FaultActivationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FaultActivationReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FaultActivationReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    java.util.List<java.lang.String>
        getFaultPamList();
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    int getFaultPamCount();
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    java.lang.String getFaultPam(int index);
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    com.google.protobuf.ByteString
        getFaultPamBytes(int index);

    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    java.util.List<java.lang.String>
        getRunTriggerList();
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    int getRunTriggerCount();
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    java.lang.String getRunTrigger(int index);
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    com.google.protobuf.ByteString
        getRunTriggerBytes(int index);
  }
  /**
   * Protobuf type {@code FaultActivationReply}
   */
  public  static final class FaultActivationReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FaultActivationReply)
      FaultActivationReplyOrBuilder {
    // Use FaultActivationReply.newBuilder() to construct.
    private FaultActivationReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FaultActivationReply() {
      faultPam_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      runTrigger_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FaultActivationReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                faultPam_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              faultPam_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                runTrigger_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              runTrigger_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          faultPam_ = faultPam_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          runTrigger_ = runTrigger_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zermia.proto.ProtoRuntime.internal_static_FaultActivationReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zermia.proto.ProtoRuntime.internal_static_FaultActivationReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zermia.proto.ProtoRuntime.FaultActivationReply.class, zermia.proto.ProtoRuntime.FaultActivationReply.Builder.class);
    }

    public static final int FAULTPAM_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList faultPam_;
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFaultPamList() {
      return faultPam_;
    }
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    public int getFaultPamCount() {
      return faultPam_.size();
    }
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    public java.lang.String getFaultPam(int index) {
      return faultPam_.get(index);
    }
    /**
     * <pre>
     * more than one fault and parameter
     * </pre>
     *
     * <code>repeated string faultPam = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFaultPamBytes(int index) {
      return faultPam_.getByteString(index);
    }

    public static final int RUNTRIGGER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList runTrigger_;
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRunTriggerList() {
      return runTrigger_;
    }
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    public int getRunTriggerCount() {
      return runTrigger_.size();
    }
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    public java.lang.String getRunTrigger(int index) {
      return runTrigger_.get(index);
    }
    /**
     * <code>repeated string runTrigger = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRunTriggerBytes(int index) {
      return runTrigger_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < faultPam_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, faultPam_.getRaw(i));
      }
      for (int i = 0; i < runTrigger_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, runTrigger_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < faultPam_.size(); i++) {
          dataSize += computeStringSizeNoTag(faultPam_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFaultPamList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < runTrigger_.size(); i++) {
          dataSize += computeStringSizeNoTag(runTrigger_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRunTriggerList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zermia.proto.ProtoRuntime.FaultActivationReply)) {
        return super.equals(obj);
      }
      zermia.proto.ProtoRuntime.FaultActivationReply other = (zermia.proto.ProtoRuntime.FaultActivationReply) obj;

      boolean result = true;
      result = result && getFaultPamList()
          .equals(other.getFaultPamList());
      result = result && getRunTriggerList()
          .equals(other.getRunTriggerList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getFaultPamCount() > 0) {
        hash = (37 * hash) + FAULTPAM_FIELD_NUMBER;
        hash = (53 * hash) + getFaultPamList().hashCode();
      }
      if (getRunTriggerCount() > 0) {
        hash = (37 * hash) + RUNTRIGGER_FIELD_NUMBER;
        hash = (53 * hash) + getRunTriggerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zermia.proto.ProtoRuntime.FaultActivationReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zermia.proto.ProtoRuntime.FaultActivationReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FaultActivationReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FaultActivationReply)
        zermia.proto.ProtoRuntime.FaultActivationReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zermia.proto.ProtoRuntime.FaultActivationReply.class, zermia.proto.ProtoRuntime.FaultActivationReply.Builder.class);
      }

      // Construct using zermia.proto.ProtoRuntime.FaultActivationReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        faultPam_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        runTrigger_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zermia.proto.ProtoRuntime.internal_static_FaultActivationReply_descriptor;
      }

      public zermia.proto.ProtoRuntime.FaultActivationReply getDefaultInstanceForType() {
        return zermia.proto.ProtoRuntime.FaultActivationReply.getDefaultInstance();
      }

      public zermia.proto.ProtoRuntime.FaultActivationReply build() {
        zermia.proto.ProtoRuntime.FaultActivationReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zermia.proto.ProtoRuntime.FaultActivationReply buildPartial() {
        zermia.proto.ProtoRuntime.FaultActivationReply result = new zermia.proto.ProtoRuntime.FaultActivationReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          faultPam_ = faultPam_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.faultPam_ = faultPam_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          runTrigger_ = runTrigger_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.runTrigger_ = runTrigger_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zermia.proto.ProtoRuntime.FaultActivationReply) {
          return mergeFrom((zermia.proto.ProtoRuntime.FaultActivationReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zermia.proto.ProtoRuntime.FaultActivationReply other) {
        if (other == zermia.proto.ProtoRuntime.FaultActivationReply.getDefaultInstance()) return this;
        if (!other.faultPam_.isEmpty()) {
          if (faultPam_.isEmpty()) {
            faultPam_ = other.faultPam_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFaultPamIsMutable();
            faultPam_.addAll(other.faultPam_);
          }
          onChanged();
        }
        if (!other.runTrigger_.isEmpty()) {
          if (runTrigger_.isEmpty()) {
            runTrigger_ = other.runTrigger_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRunTriggerIsMutable();
            runTrigger_.addAll(other.runTrigger_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zermia.proto.ProtoRuntime.FaultActivationReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zermia.proto.ProtoRuntime.FaultActivationReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList faultPam_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFaultPamIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          faultPam_ = new com.google.protobuf.LazyStringArrayList(faultPam_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFaultPamList() {
        return faultPam_.getUnmodifiableView();
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public int getFaultPamCount() {
        return faultPam_.size();
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public java.lang.String getFaultPam(int index) {
        return faultPam_.get(index);
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFaultPamBytes(int index) {
        return faultPam_.getByteString(index);
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public Builder setFaultPam(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFaultPamIsMutable();
        faultPam_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public Builder addFaultPam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFaultPamIsMutable();
        faultPam_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public Builder addAllFaultPam(
          java.lang.Iterable<java.lang.String> values) {
        ensureFaultPamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, faultPam_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public Builder clearFaultPam() {
        faultPam_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * more than one fault and parameter
       * </pre>
       *
       * <code>repeated string faultPam = 1;</code>
       */
      public Builder addFaultPamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFaultPamIsMutable();
        faultPam_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList runTrigger_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRunTriggerIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          runTrigger_ = new com.google.protobuf.LazyStringArrayList(runTrigger_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRunTriggerList() {
        return runTrigger_.getUnmodifiableView();
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public int getRunTriggerCount() {
        return runTrigger_.size();
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public java.lang.String getRunTrigger(int index) {
        return runTrigger_.get(index);
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRunTriggerBytes(int index) {
        return runTrigger_.getByteString(index);
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public Builder setRunTrigger(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunTriggerIsMutable();
        runTrigger_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public Builder addRunTrigger(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunTriggerIsMutable();
        runTrigger_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public Builder addAllRunTrigger(
          java.lang.Iterable<java.lang.String> values) {
        ensureRunTriggerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, runTrigger_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public Builder clearRunTrigger() {
        runTrigger_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string runTrigger = 2;</code>
       */
      public Builder addRunTriggerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRunTriggerIsMutable();
        runTrigger_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FaultActivationReply)
    }

    // @@protoc_insertion_point(class_scope:FaultActivationReply)
    private static final zermia.proto.ProtoRuntime.FaultActivationReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zermia.proto.ProtoRuntime.FaultActivationReply();
    }

    public static zermia.proto.ProtoRuntime.FaultActivationReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FaultActivationReply>
        PARSER = new com.google.protobuf.AbstractParser<FaultActivationReply>() {
      public FaultActivationReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FaultActivationReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FaultActivationReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FaultActivationReply> getParserForType() {
      return PARSER;
    }

    public zermia.proto.ProtoRuntime.FaultActivationReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectionReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectionReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaultActivationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaultActivationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaultActivationReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaultActivationReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoRuntime.proto\"&\n\021ConnectionReques" +
      "t\022\021\n\treplicaID\030\001 \001(\t\"B\n\017ConnectionReply\022" +
      "\030\n\020connectionStatus\030\001 \001(\010\022\025\n\rreplicaStat" +
      "us\030\002 \001(\010\"?\n\026FaultActivationRequest\022\021\n\tre" +
      "plicaID\030\001 \001(\t\022\022\n\ncurrentRun\030\002 \001(\005\"<\n\024Fau" +
      "ltActivationReply\022\020\n\010faultPam\030\001 \003(\t\022\022\n\nr" +
      "unTrigger\030\002 \003(\t2\215\001\n\016ZermiaServices\0229\n\017Fi" +
      "rstConnection\022\022.ConnectionRequest\032\020.Conn" +
      "ectionReply\"\000\022@\n\014FaultService\022\027.FaultAct" +
      "ivationRequest\032\025.FaultActivationReply\"\000B",
      "\016\n\014zermia.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectionRequest_descriptor,
        new java.lang.String[] { "ReplicaID", });
    internal_static_ConnectionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConnectionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectionReply_descriptor,
        new java.lang.String[] { "ConnectionStatus", "ReplicaStatus", });
    internal_static_FaultActivationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FaultActivationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaultActivationRequest_descriptor,
        new java.lang.String[] { "ReplicaID", "CurrentRun", });
    internal_static_FaultActivationReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FaultActivationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaultActivationReply_descriptor,
        new java.lang.String[] { "FaultPam", "RunTrigger", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
